version: 0.2
env:
  variables:
    APP_NAME: "My-App"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now..
      #- aws s3 sync . s3://my-app-buck/My-App --delete
      - pwd
      #- sudo apt install zip
      - zip -r MyAppArt.zip *
      - find . -type f -not \( -name 'MyAppArt.zip' \) -delete
      - ls -la
      #- aws s3 sync . s3://my-app-buck/ --delete
      - aws s3 cp MyAppArt.zip s3://my-app-buck/
      - pwd
      - echo Build success.
      